// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDL0BRc8CSMBV0I4vPcTr3fdliGvRiUCqg',
    appId: '1:255655300815:web:ff1f3f02e7da328602b1ba',
    messagingSenderId: '255655300815',
    projectId: 'pushnotifications-684d8',
    authDomain: 'pushnotifications-684d8.firebaseapp.com',
    storageBucket: 'pushnotifications-684d8.appspot.com',
    measurementId: 'G-LMZJTEP70Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlzIr4iA5wNdMw3dLCh9vasnvaTiU3hmI',
    appId: '1:255655300815:android:51cd1f4667b9941002b1ba',
    messagingSenderId: '255655300815',
    projectId: 'pushnotifications-684d8',
    storageBucket: 'pushnotifications-684d8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBd_SvvGegF6JnZ1ekgi4N9ae9wFcQHgbo',
    appId: '1:255655300815:ios:3f7a91155cbce24f02b1ba',
    messagingSenderId: '255655300815',
    projectId: 'pushnotifications-684d8',
    storageBucket: 'pushnotifications-684d8.appspot.com',
    iosBundleId: 'com.example.pushNotifi',
  );
}
